const { test, expect} = require('@playwright/test')
const {HomePage} = require('../pages/homepage')
const {LaptopsAndNotebooksPage} = require('../pages/laptops_and_notebooks_page')
const {ProductPage} = require('../pages/product_page')
const {CommonMenuPage} = require('../pages/common_menu_page')
const {CheckOutPage} = require('../pages/checkout_page')
const {CheckoutSuccessPage} = require('../pages/checkout_success_page')


test('Verify the user can place an order as a guest', async ({page}) => {
    await page.goto('')
    const hp = new HomePage(page)
    await hp.click_on_laptops_and_notebooks_tab()
    await hp.click_on_show_all_laptops_and_notebooks_link()
    const lanp = new LaptopsAndNotebooksPage(page)
    await lanp.click_on_add_to_cart_btn()
    const propage = new ProductPage(page)
    await propage.click_on_add_to_cart_btn()
    const cmp = new CommonMenuPage(page)
    await cmp.click_on_shopping_cart_btn()
    await propage.click_on_checkout_btn()
    const cop = new CheckOutPage(page)
    await cop.click_on_guest_checkout_radio_btn()
    await cop.click_on_continue_btn()
    await cop.enter_first_name("SuperMan")
    await cop.enter_last_name("Kent")
    await cop.enter_email("dummyem@test.com")
    await cop.enter_telephone('1234567890')
    await cop.enter_address1("Abc Avenue Litle Flower")
    await cop.enter_city('Mehsana')
    await cop.enter_postcode('351125')
    await cop.select_country_from_drpdwn('India')
    await cop.select_state_from_drpdwn('Kerala')
    await cop.click_on_continue_btn2()
    await cop.click_on_continue_btn_shipping()
    await cop.click_on_terms_and_conditions_checbox()
    await cop.click_on_continue_btn_payment()
    await cop.click_on_confirm_order_btn()
    const csp = new CheckoutSuccessPage(page)
    const msg = await csp.get_placed_order_msg()
    expect(msg).toBe('Your order has been successfully processed!')

})